/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LOGIN;

import MENUS.MainAlumno;
import MENUS.MainEmpleado;
import SQL.MetodosSQL;
import javax.swing.ImageIcon;

/**
 *
 * @author edgar
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/IMG/Logo.png")).getImage());
        setTitle("MoviTec"); 
    }
    
    MetodosSQL metodos = new MetodosSQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JInfoLogin = new javax.swing.JPanel();
        LUsuario = new java.awt.Label();
        JUsuario = new java.awt.TextField();
        JContraseña = new javax.swing.JPasswordField();
        LContraseña = new java.awt.Label();
        BtnEntrar = new javax.swing.JButton();
        JBarraLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JInfoLogin.setBackground(new java.awt.Color(255, 255, 255));

        LUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LUsuario.setText("No.Control");

        JContraseña.setBackground(new java.awt.Color(255, 255, 255));

        LContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LContraseña.setText("Contraseña");

        BtnEntrar.setBackground(new java.awt.Color(0, 102, 255));
        BtnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JInfoLoginLayout = new javax.swing.GroupLayout(JInfoLogin);
        JInfoLogin.setLayout(JInfoLoginLayout);
        JInfoLoginLayout.setHorizontalGroup(
            JInfoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JInfoLoginLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(JInfoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        JInfoLoginLayout.setVerticalGroup(
            JInfoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JInfoLoginLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(LUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(LContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(JContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        LUsuario.getAccessibleContext().setAccessibleName("ho");

        getContentPane().add(JInfoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 570, 510));

        JBarraLogin.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INICIO SESION");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logon2.png"))); // NOI18N

        javax.swing.GroupLayout JBarraLoginLayout = new javax.swing.GroupLayout(JBarraLogin);
        JBarraLogin.setLayout(JBarraLoginLayout);
        JBarraLoginLayout.setHorizontalGroup(
            JBarraLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JBarraLoginLayout.createSequentialGroup()
                .addGroup(JBarraLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JBarraLoginLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(JBarraLoginLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JBarraLoginLayout.setVerticalGroup(
            JBarraLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JBarraLoginLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
        );

        getContentPane().add(JBarraLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
  
        metodos.BuscarUsuario(JUsuario.getText(),JContraseña.getText());
    
        if("Alumno".equals(MetodosSQL.TipoUsuario)){
         metodos.obtenerDatosAlumno(JUsuario.getText());
         new MainAlumno().setVisible(true);
          dispose();
        }
        if("Coordinador".equals(MetodosSQL.TipoUsuario) || "Jefe".equals(MetodosSQL.TipoUsuario) ||"Extraescolares".equals(MetodosSQL.TipoUsuario)){
         metodos.obtenerDatosEmpleado(JUsuario.getText());
         new MainEmpleado().setVisible(true);
          dispose();
        }
 
        MetodosSQL.TipoUsuario ="";

// TODO add your handling code here:
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
 

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JPanel JBarraLogin;
    private javax.swing.JPasswordField JContraseña;
    private javax.swing.JPanel JInfoLogin;
    private java.awt.TextField JUsuario;
    private java.awt.Label LContraseña;
    private java.awt.Label LUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
