/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MENUS;

import javax.swing.*;
import LOGIN.Login;
import SQL.MetodosSQL;
import static SQL.MetodosSQL.datos;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public final class MainAlumno extends javax.swing.JFrame {
        
    public MainAlumno() {
        initComponents();
        setLocationRelativeTo(null);      
        setTitle("MoviTec Alumno");
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/IMG/Logo.png")).getImage());
        PanelPrincipal.removeAll();
        PanelPrincipal.add(JPerfil);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();  
        RellenarDatosPerfil();String[] institutos = MetodosSQL.obtenerDatosEscuela(JTnocontrol.getText()); // Reemplaza noControlAlumno con el valor correspondiente
        JcInstitutos.setModel(new DefaultComboBoxModel<>(institutos));
    }
      

    public void RellenarDatosPerfil(){ 
        JTnocontrol.setText(datos[0]);
        JTnombre.setText(datos[1]);
        JTapellido.setText(datos[2]);
        JTcurp.setText(datos[3]);
        JTtelefono.setText(datos[4]);
        JTcorreo.setText(datos[5]);
        JTinstituto.setText(datos[6]);
        JTcarrera.setText(datos[7]);
        JTsemestre.setText(datos[8]);
        JTpromedio.setText(datos[9]);
        JTadeudos.setText(datos[10]);
        JTrc.setText(datos[11]);  
        jTMovilidades.setText(datos[12]); 
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMenuBarra = new javax.swing.JPanel();
        BtnPerfil = new javax.swing.JButton();
        BtnSolicitar = new javax.swing.JButton();
        BtnEstatus = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JTabbedPane();
        JPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTapellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTnocontrol = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SEMESTRE = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JTcurp = new javax.swing.JTextField();
        JTcarrera = new javax.swing.JTextField();
        JTtelefono = new javax.swing.JTextField();
        JTcorreo = new javax.swing.JTextField();
        JTinstituto = new javax.swing.JTextField();
        JTsemestre = new javax.swing.JTextField();
        JTadeudos = new javax.swing.JTextField();
        JTrc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JTpromedio = new javax.swing.JTextField();
        JNoMovilidades = new javax.swing.JLabel();
        jTMovilidades = new javax.swing.JTextField();
        JSolicitud = new javax.swing.JPanel();
        InstitutoInteres = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        JcInstitutos = new javax.swing.JComboBox<>();
        Materias = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        JcMateria = new javax.swing.JComboBox<>();
        BtnMas = new javax.swing.JButton();
        BtnMenos = new javax.swing.JButton();
        BtnConfirmarEscuela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JMovilidades = new javax.swing.JPanel();
        JLSolicitud = new javax.swing.JLabel();
        BtnCancelarSoli = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaPlanEstudios = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaMovilidades = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        JEstatusSolicitud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JMenuBarra.setBackground(new java.awt.Color(51, 102, 255));

        BtnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPerfil.setForeground(new java.awt.Color(51, 102, 255));
        BtnPerfil.setText("PERFIL");
        BtnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPerfilActionPerformed(evt);
            }
        });

        BtnSolicitar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSolicitar.setForeground(new java.awt.Color(51, 102, 255));
        BtnSolicitar.setText("SOLICITAR");
        BtnSolicitar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnSolicitar.setBorderPainted(false);
        BtnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSolicitarActionPerformed(evt);
            }
        });

        BtnEstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEstatus.setForeground(new java.awt.Color(51, 102, 255));
        BtnEstatus.setText("ESTATUS");
        BtnEstatus.setBorder(null);
        BtnEstatus.setBorderPainted(false);
        BtnEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstatusActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(51, 102, 255));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Salir.png"))); // NOI18N
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JMenuBarraLayout = new javax.swing.GroupLayout(JMenuBarra);
        JMenuBarra.setLayout(JMenuBarraLayout);
        JMenuBarraLayout.setHorizontalGroup(
            JMenuBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JMenuBarraLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JMenuBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JMenuBarraLayout.createSequentialGroup()
                        .addComponent(BtnSalir)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JMenuBarraLayout.createSequentialGroup()
                        .addGroup(JMenuBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        JMenuBarraLayout.setVerticalGroup(
            JMenuBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JMenuBarraLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BtnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BtnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BtnEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addGap(32, 32, 32))
        );

        getContentPane().add(JMenuBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 580));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        JPerfil.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Perfiles.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("DATOS PERSONALES: ");

        jLabel6.setText("NOMBRE:");

        JTnombre.setEditable(false);

        jLabel7.setText("APELLIDO:");

        JTapellido.setEditable(false);

        jLabel8.setText("NO. CONTROL:");

        JTnocontrol.setEditable(false);

        jLabel9.setText("CURP:");

        jLabel10.setText("TELEFONO:");

        jLabel11.setText("CORREO:");

        jLabel12.setText("INSTITUTO:");

        jLabel13.setText("CARRERA:");

        SEMESTRE.setText("SEMESTRE:");

        jLabel14.setText("ESTATUS ADEUDOS:");

        jLabel15.setText("ESTATUS RC:");

        JTcurp.setEditable(false);
        JTcurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcurpActionPerformed(evt);
            }
        });

        JTcarrera.setEditable(false);

        JTtelefono.setEditable(false);

        JTcorreo.setEditable(false);

        JTinstituto.setEditable(false);

        JTsemestre.setEditable(false);

        JTadeudos.setEditable(false);

        JTrc.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("DATOS EDUCATIVOS: ");

        jLabel19.setText("Promedio:");

        JTpromedio.setEditable(false);

        JNoMovilidades.setText("No.Movilidades:");

        jTMovilidades.setEditable(false);

        javax.swing.GroupLayout JPerfilLayout = new javax.swing.GroupLayout(JPerfil);
        JPerfil.setLayout(JPerfilLayout);
        JPerfilLayout.setHorizontalGroup(
            JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPerfilLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPerfilLayout.createSequentialGroup()
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addGroup(JPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(12, 12, 12)))
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JTtelefono)
                            .addComponent(JTapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(140, 140, 140)
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53))
                            .addGroup(JPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTnocontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(JPerfilLayout.createSequentialGroup()
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(20, 20, 20)
                                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTcurp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JPerfilLayout.createSequentialGroup()
                                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTinstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPerfilLayout.createSequentialGroup()
                                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JTrc)
                                            .addComponent(JTadeudos, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                                .addGap(41, 41, 41)
                                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(SEMESTRE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPerfilLayout.createSequentialGroup()
                                        .addComponent(JNoMovilidades)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTMovilidades, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(127, 127, 127))))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPerfilLayout.createSequentialGroup()
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPerfilLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPerfilLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel16)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPerfilLayout.setVerticalGroup(
            JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPerfilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(JTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPerfilLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JTnocontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPerfilLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(JTcurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel16)
                .addGap(47, 47, 47)
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JTinstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(JTcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEMESTRE)
                    .addComponent(JTsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTadeudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(JTpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JTrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNoMovilidades)
                    .addComponent(jTMovilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("", JPerfil);

        JSolicitud.setBackground(new java.awt.Color(255, 255, 255));

        InstitutoInteres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InstitutoInteres.setText("INSTITUTO DE INTERES:");

        BtnConfirmar.setBackground(new java.awt.Color(0, 102, 255));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Confirmar.png"))); // NOI18N
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(0, 102, 255));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Cancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        JcInstitutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcInstitutosActionPerformed(evt);
            }
        });

        Materias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Materias.setText("MATERIAS OFERTADAS:");

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MATERIA", "NO. CREDITOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableMaterias);
        if (jTableMaterias.getColumnModel().getColumnCount() > 0) {
            jTableMaterias.getColumnModel().getColumn(0).setResizable(false);
            jTableMaterias.getColumnModel().getColumn(1).setResizable(false);
            jTableMaterias.getColumnModel().getColumn(2).setResizable(false);
        }

        BtnMas.setBackground(new java.awt.Color(0, 102, 255));
        BtnMas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMas.setForeground(new java.awt.Color(255, 255, 255));
        BtnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mas.png"))); // NOI18N
        BtnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasActionPerformed(evt);
            }
        });

        BtnMenos.setBackground(new java.awt.Color(0, 102, 255));
        BtnMenos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMenos.setForeground(new java.awt.Color(255, 255, 255));
        BtnMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/menos.png"))); // NOI18N
        BtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenosActionPerformed(evt);
            }
        });

        BtnConfirmarEscuela.setBackground(new java.awt.Color(0, 102, 255));
        BtnConfirmarEscuela.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnConfirmarEscuela.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmarEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Flecha.png"))); // NOI18N
        BtnConfirmarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarEscuelaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SOLICITUD DE MOVLIDAD ESTUDIANTIL");

        javax.swing.GroupLayout JSolicitudLayout = new javax.swing.GroupLayout(JSolicitud);
        JSolicitud.setLayout(JSolicitudLayout);
        JSolicitudLayout.setHorizontalGroup(
            JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JSolicitudLayout.createSequentialGroup()
                .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JSolicitudLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(BtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JSolicitudLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JSolicitudLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InstitutoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Materias))
                        .addGap(18, 18, 18)
                        .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JSolicitudLayout.createSequentialGroup()
                                .addComponent(JcInstitutos, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnConfirmarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JSolicitudLayout.createSequentialGroup()
                                .addComponent(JcMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(BtnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JSolicitudLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        JSolicitudLayout.setVerticalGroup(
            JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JSolicitudLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(67, 67, 67)
                .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JSolicitudLayout.createSequentialGroup()
                        .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InstitutoInteres)
                            .addComponent(JcInstitutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JSolicitudLayout.createSequentialGroup()
                        .addComponent(BtnConfirmarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JSolicitudLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JcMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Materias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JSolicitudLayout.createSequentialGroup()
                        .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(JSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        PanelPrincipal.addTab("", JSolicitud);

        JMovilidades.setBackground(new java.awt.Color(255, 255, 255));

        JLSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLSolicitud.setText("ESTATUS DE SOLICITUD:");

        BtnCancelarSoli.setBackground(new java.awt.Color(0, 102, 255));
        BtnCancelarSoli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelarSoli.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelarSoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Cancelar.png"))); // NOI18N
        BtnCancelarSoli.setText("Cancelar Solicitud");
        BtnCancelarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarSoliActionPerformed(evt);
            }
        });

        TablaPlanEstudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MATERIAS"
            }
        ));
        jScrollPane4.setViewportView(TablaPlanEstudios);
        TablaPlanEstudios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        TablaMovilidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Fecha solicitud", "Alumno", "Instituto de destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TablaMovilidades);
        if (TablaMovilidades.getColumnModel().getColumnCount() > 0) {
            TablaMovilidades.getColumnModel().getColumn(0).setResizable(false);
            TablaMovilidades.getColumnModel().getColumn(1).setResizable(false);
            TablaMovilidades.getColumnModel().getColumn(2).setResizable(false);
            TablaMovilidades.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("DETALLE DE SOLICITUD");

        JEstatusSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JEstatusSolicitud.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout JMovilidadesLayout = new javax.swing.GroupLayout(JMovilidades);
        JMovilidades.setLayout(JMovilidadesLayout);
        JMovilidadesLayout.setHorizontalGroup(
            JMovilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JMovilidadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelarSoli)
                .addGap(20, 20, 20))
            .addGroup(JMovilidadesLayout.createSequentialGroup()
                .addGroup(JMovilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JMovilidadesLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(JMovilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JMovilidadesLayout.createSequentialGroup()
                                .addComponent(JLSolicitud)
                                .addGap(26, 26, 26)
                                .addComponent(JEstatusSolicitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JMovilidadesLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel17)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        JMovilidadesLayout.setVerticalGroup(
            JMovilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JMovilidadesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel17)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(JMovilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JMovilidadesLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(JMovilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLSolicitud)
                            .addComponent(JEstatusSolicitud))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(BtnCancelarSoli, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        PanelPrincipal.addTab("", JMovilidades);

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, -29, 870, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
  int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas cerrar tu sesión?", "Confirmación de salida", JOptionPane.YES_NO_OPTION);
       if (respuesta == JOptionPane.YES_OPTION) {
           new Login().setVisible(true);
           dispose();
           
      }
               // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSolicitarActionPerformed
        PanelPrincipal.removeAll();
        PanelPrincipal.add(JSolicitud);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();   
        BtnCancelar.setEnabled(false);
        
      
       
    }//GEN-LAST:event_BtnSolicitarActionPerformed

    
    
    private void BtnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPerfilActionPerformed
        PanelPrincipal.removeAll();
        PanelPrincipal.add(JPerfil);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint(); 
           
// TODO add your handling code here:
    }//GEN-LAST:event_BtnPerfilActionPerformed

    
    
    
    private void BtnEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstatusActionPerformed
        PanelPrincipal.removeAll();
        PanelPrincipal.add(JMovilidades);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();  

        DefaultTableModel modeloTabla = (DefaultTableModel) TablaMovilidades.getModel();
        modeloTabla.setRowCount(0);
        MetodosSQL.SeleccionarUltimaSolicitudAlumno(TablaMovilidades, JTnocontrol.getText());

        if (modeloTabla.getRowCount() > 0) {
            MetodosSQL.mostrarMaterias(TablaPlanEstudios, TablaMovilidades);
            TablaPlanEstudios.enable(false);
        } else {
            // Realiza alguna acción si no hay datos en la tabla, por ejemplo:
             JOptionPane.showMessageDialog(null, "No se encontraron solicitudes de movilidad para el alumno.");
        }

String estatus = MetodosSQL.SeleccionarUltimaSolicitudAlumno(TablaMovilidades, JTnocontrol.getText());

if (estatus != null) {
    switch (estatus) {
        case "Aceptado":
            JEstatusSolicitud.setText(estatus);
            JEstatusSolicitud.setForeground(Color.GREEN);
            break;
        case "En Revisión":
            JEstatusSolicitud.setText(estatus);
            JEstatusSolicitud.setForeground(Color.GRAY);
            break;
        case "Rechazado":
            JEstatusSolicitud.setText(estatus);
            JEstatusSolicitud.setForeground(Color.RED);
            break;
        case "Cancelado":
            JEstatusSolicitud.setText(estatus);
            JEstatusSolicitud.setForeground(new Color(128, 0, 128)); // Púrpura
            break;
        default:
            JEstatusSolicitud.setText("");
            JEstatusSolicitud.setForeground(Color.BLACK);
            break;
    }
}else{
    JEstatusSolicitud.setText("");
    JEstatusSolicitud.setForeground(Color.BLACK);
  }
    }//GEN-LAST:event_BtnEstatusActionPerformed

    
    
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
      int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas cancelar la solicitud?", "Cancelación de solicitud", JOptionPane.YES_NO_OPTION);
      if (respuesta == JOptionPane.YES_OPTION) { 
 
          JcInstitutos.setEnabled(true);
          DefaultTableModel modeloTabla = (DefaultTableModel) jTableMaterias.getModel();
          modeloTabla.setRowCount(0);
          JcMateria.removeAllItems();
          BtnCancelar.setEnabled(false);
          
      }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    
    
    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed

        
      String estatus = MetodosSQL.SeleccionarUltimaSolicitudAlumno(TablaMovilidades, JTnocontrol.getText());
    if (estatus == null || estatus.equalsIgnoreCase("Cancelado")|| estatus.equalsIgnoreCase("Rechazado")) {
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas Confirmar la solicitud?", "Confirmación de solicitud", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            // Restricciones de negocio
            if(jTableMaterias.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "Solicitud Incompleta\n\nLlena todos los campos", "Error", JOptionPane.ERROR_MESSAGE);     
           } else if (Integer.parseInt(JTrc.getText()) >= 1) {
                JOptionPane.showMessageDialog(null, "Solicitud Denegada\n\nMotivo: Materias en RC", "Error", JOptionPane.ERROR_MESSAGE);
           } else if (JTadeudos.getText().trim().equalsIgnoreCase("Adeudado")) {
                JOptionPane.showMessageDialog(null, "Solicitud Denegada\n\nMotivo: Se tienen Adeudos", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.parseInt(jTMovilidades.getText()) >= 3) {
                JOptionPane.showMessageDialog(null, "Solicitud Denegada\n\nMotivo: Numero de Movilidades Superado", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                MetodosSQL.InsertarMovilidad(JTnocontrol.getText(), (String) JcInstitutos.getSelectedItem());
                MetodosSQL.InsertarMateriasMovilidad(jTableMaterias);
                JcInstitutos.setEnabled(true);
                DefaultTableModel modeloTabla = (DefaultTableModel) jTableMaterias.getModel();
                modeloTabla.setRowCount(0);
                JcMateria.removeAllItems();
                BtnCancelar.setEnabled(false);
            }
        }
    } else {
        if (estatus.equalsIgnoreCase("En Revisión")) {
            JOptionPane.showMessageDialog(null, "Ya tienes una solicitud en proceso");
        } else if (estatus.equalsIgnoreCase("Aceptado")) {
            JOptionPane.showMessageDialog(null, "Ya tienes una solicitud Aceptada");
        }
    }
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    
    
    private void JTcurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcurpActionPerformed

    private void BtnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasActionPerformed
      MetodosSQL.AgregarMaterias(jTableMaterias,(String)JcMateria.getSelectedItem()); 
    }//GEN-LAST:event_BtnMasActionPerformed

    private void BtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenosActionPerformed
       MetodosSQL.EliminarMaterias(jTableMaterias);  
    }//GEN-LAST:event_BtnMenosActionPerformed


    
    
    
    private void BtnConfirmarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarEscuelaActionPerformed
     
       String[] materias = MetodosSQL.obtenerDatosMaterias(JTcarrera.getText(),(String)JcInstitutos.getSelectedItem()); // Reemplaza noControlAlumno con el valor correspondiente
       JcMateria.setModel(new DefaultComboBoxModel<>(materias));
       JcInstitutos.setEnabled(false);
       BtnCancelar.setEnabled(true);
    }//GEN-LAST:event_BtnConfirmarEscuelaActionPerformed

    
    
    
    private void BtnCancelarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarSoliActionPerformed
     
       String estatus = MetodosSQL.SeleccionarUltimaSolicitudAlumno(TablaMovilidades, JTnocontrol.getText());
       
       if(estatus==null){    
           JOptionPane.showMessageDialog(null, "No existe una solicitud");
       }else{
         if(estatus.equalsIgnoreCase("Cancelado")){
              BtnCancelar.disable();
          }else{ 
        
      int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas Cancelar la solicitud?", "Confirmación de solicitud", JOptionPane.YES_NO_OPTION);
      if (respuesta == JOptionPane.YES_OPTION) { 
              MetodosSQL.modificarEstatusCancelado(JTnocontrol.getText());            
              JEstatusSolicitud.setText("Cancelado");
              JEstatusSolicitud.setForeground(new Color(128, 0, 128)); // Púrpura
              
              
          }
         }
         } 
    }//GEN-LAST:event_BtnCancelarSoliActionPerformed

    private void JcInstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcInstitutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcInstitutosActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnCancelarSoli;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnConfirmarEscuela;
    private javax.swing.JButton BtnEstatus;
    private javax.swing.JButton BtnMas;
    private javax.swing.JButton BtnMenos;
    private javax.swing.JButton BtnPerfil;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSolicitar;
    private javax.swing.JLabel InstitutoInteres;
    private javax.swing.JLabel JEstatusSolicitud;
    private javax.swing.JLabel JLSolicitud;
    private javax.swing.JPanel JMenuBarra;
    private javax.swing.JPanel JMovilidades;
    private javax.swing.JLabel JNoMovilidades;
    private javax.swing.JPanel JPerfil;
    private javax.swing.JPanel JSolicitud;
    private javax.swing.JTextField JTadeudos;
    private javax.swing.JTextField JTapellido;
    private javax.swing.JTextField JTcarrera;
    private javax.swing.JTextField JTcorreo;
    private javax.swing.JTextField JTcurp;
    private javax.swing.JTextField JTinstituto;
    private javax.swing.JTextField JTnocontrol;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JTextField JTpromedio;
    private javax.swing.JTextField JTrc;
    private javax.swing.JTextField JTsemestre;
    private javax.swing.JTextField JTtelefono;
    private javax.swing.JComboBox<String> JcInstitutos;
    private javax.swing.JComboBox<String> JcMateria;
    private javax.swing.JLabel Materias;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JLabel SEMESTRE;
    private javax.swing.JTable TablaMovilidades;
    private javax.swing.JTable TablaPlanEstudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTMovilidades;
    private javax.swing.JTable jTableMaterias;
    // End of variables declaration//GEN-END:variables
}
